version: "3"

services:
  db:
    image: mysql:8.0.17
    container_name: trade-mysql-test
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password!"
    volumes:
      - "./docker-compose-mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "./sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql"
