#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost/trade?characterEncoding=utf8
    username: root
    password: password!
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

file:
  location: /Users/sclee/sclee/works/tmp/images