#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost/commerce?characterEncoding=utf8
    username: sclee
    password: password!
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    enabled: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml